"""add_reminders_tables

Revision ID: d19bfb2fd00b
Revises: 2606f95e56dd
Create Date: 2026-02-14 16:14:54.275630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd19bfb2fd00b'
down_revision: Union[str, Sequence[str], None] = '2606f95e56dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recurrence_type', sa.String(length=20), nullable=False),
    sa.Column('interval_value', sa.Integer(), nullable=True),
    sa.Column('interval_unit', sa.String(length=20), nullable=True),
    sa.Column('days_of_week', sa.String(length=20), nullable=True),
    sa.Column('reminder_time', sa.Time(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('carry_over', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'reminders', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_table('reminder_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('instance_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminder_due', 'reminder_instances', ['reminder_id', 'due_date'], unique=False)
    op.create_index('idx_user_due_date_status', 'reminder_instances', ['user_id', 'due_date', 'status'], unique=False)
    op.create_index(op.f('ix_reminder_instances_id'), 'reminder_instances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_instances_id'), table_name='reminder_instances')
    op.drop_index('idx_user_due_date_status', table_name='reminder_instances')
    op.drop_index('idx_reminder_due', table_name='reminder_instances')
    op.drop_table('reminder_instances')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.drop_index('idx_user_active', table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
